version: 2
orbs: 
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    working_directory: ~/circleci-react-example/src
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/circleci-react-example
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: React build
          command: npm run build
      - aws-s3/copy:
          from: ./build/
          to: 's3://circleci-react-test'
          arguments: '--dryrun'
